### ISSUE TITLE
Proposal for a simple search page

### ISSUE THREAD

**Issue by kostasx** [HugoGiraudel/SJSJ#144]
(Enhancement)
I have created a gh-pages branch and placed a simple search page that uses the JSON data.
Please check it [here](http://kostasx.github.io/SJSJ/) and let me know If I should create a pull request.
;)

**Comment by KittyGiraudel** [comment]
Wow, that’s awesome, I love it! Would you mind submit a PR? I’ll review the design a tiny bit, add some credits to you and release it! :)

**Comment by kostasx** [comment]
Sure. One problem though. Is it possible to create a PR for the gh-pages branch, which is not available on your repo?

**Comment by KittyGiraudel** [comment]
Let me create the branch for you.

**Comment by KittyGiraudel** [comment]
Done.

**Comment by KittyGiraudel** [comment]
I love what you did, can’t wait to release it! :)

**Comment by kostasx** [comment]
Thanks. I really like the project.
Just did a PR.

**Comment by KittyGiraudel** [comment]
Seems live: http://hugogiraudel.com/SJSJ/. Thank you so much for your work, I will announce it as soon as I've double checked everything. :)

Still have some path issues.

**Comment by kostasx** [comment]
Sure. I see that the entry pages are not working.
I will keep a close eye on your updates. 
(I've just found out you'll be talking at DevIt. Have a great time in Thessaloniki!)

**Comment by KittyGiraudel** [comment]
I'll rename the branch right now as I can't investigate any longer. I'd like to buy a domain name but I need to think bout it.

**Comment by kostasx** [comment]
Fair enough.

**Comment by KittyGiraudel** [comment]
Closing this, currently in the process of getting jargon.js.org and deploying the whole thing. :)
