### ISSUE TITLE
Search icon not rendering properly

### ISSUE THREAD

**Issue by m-sureshraj** [HugoGiraudel/SJSJ#163]
Platform - ubuntu 14.04
chrome Version - 50.0.2661.94 (64-bit)
Issue - search icon show up as blank square.

![screenshot from 2016-05-11 10 14 37](https://cloud.githubusercontent.com/assets/12813750/15170187/5450fbe0-1761-11e6-8383-c28497fac7fa.png)

**Comment by KittyGiraudel** [comment]
The search icon is currently an emoji. I guess now would be a good time to
put an SVG instead. I'll do it. Thank you for reporting.

**Comment by m-sureshraj** [comment]
:+1:

**Comment by KittyGiraudel** [comment]
Should be fixed.
