### ISSUE TITLE
What is the process/guidance for editing existing definitions?

### ISSUE THREAD

**Issue by togakangaroo** [HugoGiraudel/SJSJ#173]
For example I find

> Virtual DOM: a copy of the DOM in memory that the program can modify instead of directly interfacing with the “real” DOM to help speed up interactions

to be very misleading as it implies the "real" DOM is not stored in memory,

I don't mean to pick on that specific one and I'd like to make lots of adjustments. I assume you want a PR for this, do you have any guidance however on what is/is not appropriate to edit/what level of explanation you want/the length of the summary/the length of the description?

**Comment by KittyGiraudel** [comment]
Hey there,

I guess now would be a good time for me to write some contributing guidelines on what is expected for an entry. Here is how I picture things.

The description should be relatively concise (between 80 and 200 characters I would say) and aims at providing a tiny insight at what the word actually means. It should not contain any technical consideration for instance.

The content of the entry can be long, although I would try to keep it under 500 words. The design pattern entry for instance is a solid 2200 words and I personally find it way too long. I think for this project, short is good (less is more, as we say). I would like to avoid having anything below 100-150 words however, as it seems a bit short to me to explain something with enough detail that anyone could understand it. Also, I can imagine the frustration of a user clicking on an entry after having read the description, only to find themselves with the exact same description as only content…

The content itself should be simple to understand. The idea being to explain JS jargon, an entry should not contain even more buzzwords and complex patterns and ideas; that would defeat the purpose. Of course we are right to expect a bit of technical knowledge from users, but we should be able to explain these words and ideas with simplicity. Long story short, an entry is not the right place to brag with technical experience, at least not if it makes the content harder to grasp.

An entry can contain images, and code, by all mean if it helps understand the idea behind it. It’s also a good place to add some further readings if we think that could help.

I hope this helps? I’ll write a more official document to sum this up soon. :)

**Comment by KittyGiraudel** [comment]
Done with https://github.com/HugoGiraudel/SJSJ/commit/fe57b9d87c9ccb53d296f791e637d5aa665de1d5.
