### ISSUE TITLE
Flickering on Mac

### ISSUE THREAD

**Issue by NasserAlmanji** [HugoGiraudel/SJSJ#187]
Are you using this page (http://jargon.js.org) for computation?

**Comment by KittyGiraudel** [comment]
I’m not sure what you mean?

**Comment by NasserAlmanji** [comment]
I am sorry.

The page seems to be flickering in my Mac.
Maybe it is the animation.

I am sorry again.

**Comment by KittyGiraudel** [comment]
What kind of flickering are you experiencing?

**Comment by NasserAlmanji** [comment]
I don't know if I can explain flickering,
It is like you can see white flashes (detectable by the eye)

**Comment by KittyGiraudel** [comment]
Which browser are you using?

**Comment by NasserAlmanji** [comment]
Chrome on Mac

Get Outlook for Android<https://aka.ms/ghei36>



On Mon, Jan 2, 2017 at 4:20 PM +0400, "Hugo Giraudel" <notifications@github.com<mailto:notifications@github.com>> wrote:


Which browser are you using?

**Comment by KittyGiraudel** [comment]
I cannot reproduce. 🤷‍♀️
