### ISSUE TITLE
Cleanup of {}.final files

### ISSUE THREAD

**Issue by rsvp** [HugoGiraudel/SJSJ#189]
hi Hugo, recently noticed a very large number of **{hash}.final** files
under the storage folder for Firefox which do not cleanup after themselves.
They are occupying a large amount of disk space unnecessarily.

They all have your name attached, for example,
***../storage/default/https+++hugogiraudel.com/cache/morgue***
so could you kindly explain why such files should persist?

Thanks very much.

**Comment by KittyGiraudel** [comment]
Hey. I’m going to be honest, I have no idea what you are talking about. There is no `storage` folder in this repository as far as I can tell. Do you have a screenshot or something?

**Comment by rsvp** [comment]
So here's a typical directory listing, but keep in mind, there are *thousands*
of these things. Do you have any code which generates such `.final` files?
**How and why would they be used, in what context?**

```
./.mozilla/firefox/foobar.default/storage/default/https+++hugogiraudel.com/cache/morgue/106:
 total 12
 -rw------- 1 3977 Jul 16 18:35 {1bab07c7-0f32-43dd-907a-c0596ae43b6a}.final
 -rw------- 1 3068 Jul 16 18:33 {3a494acc-614d-482c-a1dc-56f00373ff6a}.final
 -rw------- 1  244 Jul 16 18:35 {e953355d-3cf4-4d21-9f7f-a60e49c4366a}.final
 
./.mozilla/firefox/foobar.default/storage/default/https+++hugogiraudel.com/cache/morgue/107:
 total 292
 -rw------- 1 275838 Jul 16 18:35 {2468bbe1-cd87-4148-a693-fe8e9347526b}.final
 -rw------- 1   6627 Jul 16 18:33 {27892ab9-5e7d-4f98-abad-c8d16ba1996b}.final
 -rw------- 1   9820 Jul 16 18:33 {a4d869cc-2e63-40fb-8a10-f4a87ce33c6b}.final
 
./.mozilla/firefox/foobar.default/storage/default/https+++hugogiraudel.com/cache/morgue/108:
 total 8
 -rw------- 1 3012 Jul 16 18:33 {05c08b28-18e5-4bf9-9a6f-ea12aa4d0a6c}.final
 -rw------- 1 3079 Jul 16 18:33 {a2246164-38e0-4304-862e-96842883106c}.final
 
./.mozilla/firefox/foobar.default/storage/default/https+++hugogiraudel.com/cache/morgue/109:
 total 84
 -rw------- 1  3998 Jul 16 18:35 {1ffd5f9e-48bd-4783-a4bd-b90c27e2f46d}.final
 -rw------- 1 40336 Jul 16 18:33 {35e54dd7-5a98-42d7-a97e-cf17d138bf6d}.final
 -rw------- 1 27333 Jul 16 18:35 {50640692-5639-440b-ade7-872eff96606d}.final
 -rw------- 1 10388 Jul 16 18:33 {d1c3d242-2049-4bf4-9a25-4bfc3cb7f06d}.final
```

There is even more stuff in upper directories with your website cited as origin,
so hopefully you can shed some light on this mystery.

**Comment by KittyGiraudel** [comment]
Alright, so this has nothing to do with SJSJ at all. Please move it to https://github.com/HugoGiraudel/hugogiraudel.com.

**Comment by rsvp** [comment]
OK, moved issue to https://github.com/HugoGiraudel/hugogiraudel.com/issues/33
but hopefully without further deflection :-)
