### ISSUE TITLE
Define Isomorphic

### ISSUE THREAD

**Issue by philipwalton** [HugoGiraudel/SJSJ#38]
When I heard of this project, the first thing I did was look to see how you defined "Isomorphic", but then it wasn't there :)

**Comment by KittyGiraudel** [comment]
Good idea.

**Comment by KittyGiraudel** [comment]
Done: https://github.com/HugoGiraudel/SJSJ/commit/0b8f9bdd9a3dcc531dbe74713e86b55ffe9a6075. :)
