### ISSUE TITLE
Subcategories?

### ISSUE THREAD

**Issue by frederikcreemers** [HugoGiraudel/SJSJ#60]
I'm not sure if subcategories are a good idea, but here's the problem I'm thinking about:

I just submitted a pull request for CORS. inside it, I'm using a lot of terms around HTTP like headers, methods (OPTIONS specifically), resources. I think it would be good to have separate entries for these. But the word `resource` has different meanings in different contexts, the same goes for the word `header`. Should I just ad these as HTTP resource and HTTP header, or could it be useful to have a HTTP category under which these entries fall?

**Comment by KittyGiraudel** [comment]
Alright. Let me think about this. :)

**Comment by eljhkrr** [comment]
Links to wikipedia might help for simple terms like HTTP header. It'll also help keep the list of terms from getting cluttered

**Comment by frederikcreemers** [comment]
Agree @TheRakken

**Comment by KittyGiraudel** [comment]
Agreed. Do you see any existing term that should be removed from the list
in favor of Wikipedia?

Le mar. 8 déc. 2015 08:59, Frederik Creemers notifications@github.com a
écrit :

**Comment by eljhkrr** [comment]
The list is ok as it is, IMO

**Comment by KittyGiraudel** [comment]
For now, I’m closing. Feel free to re-open when you firmly believe the list cannot live without categories. :)
